(function($){"use strict";$('.preloader-wrap').on('click',function(){$('.preloader-wrap').fadeOut(700)});$(window).on('load',function(){if($('.grid').length){var $masonry=$('.grid').masonry({horizontalOrder:!0,})}
setTimeout(function(){$('.preloader-wrap').fadeOut(500,function(){});$('.js-main-title-of-site').addClass('reveal-animation');$('#main-logo').addClass('logo-animation');$.each($('.count-item .title-cube-section'),function(){var count=$(this).data('count'),numAnim=new CountUp(this,0,count,0,5);var waypoints=$('.count-item').waypoint({handler:function(direction){numAnim.start()},offset:'80%'})})},2000)});$(document).ready(function(){var widthOfScrollbar;function getScrollBarWidth(){var $outer=$('<div>').css({visibility:'hidden',width:100,overflow:'scroll'}).appendTo('body'),widthWithScroll=$('<div>').css({width:'100%'}).appendTo($outer).outerWidth();$outer.remove();widthOfScrollbar=100-widthWithScroll;return 100-widthWithScroll};getScrollBarWidth();$(window).on('resize',function(){getScrollBarWidth()});$(document).on("click",".page-redirect",function(e){e.preventDefault();$("body").fadeOut(500);var self=this;setTimeout(function(){window.location.href=$(self).attr("href")},500)});$("#menu_btn--js").on("click",function(){$(this).toggleClass('open');$('#fullPageMenu').toggleClass('-open-menu');$('body').toggleClass('no-scroll');if($('#fullPageMenu').hasClass('-open-menu')){$(".header .main-logo").css({"visibility":"hidden","opacity":'0'});$(".header").addClass("-transparent-bg");if(!$('body').hasClass('fullpage-page')&&!$('body').hasClass('cube-page')){$('body, .header-wrap').css('padding-right',widthOfScrollbar);if(!$('body').hasClass('flat-page')){$('.bg-grid, .bg_letter.-page').css('right',widthOfScrollbar)}}
if($('#fullpage').length){$.fn.fullpage.setAllowScrolling(!1)}
$('.page-helper').hide()}
else{setTimeout(function(){$(".header .main-logo").css({"visibility":"visible","opacity":'1'})},600);$(".header").removeClass("-transparent-bg");if(!$('body').hasClass('fullpage-page')&&!$('body').hasClass('cube-page')){$('body, .header-wrap').css('padding-right','0');if(!$('body').hasClass('flat-page')){$('.bg-grid, .bg_letter.-page').css('right','0')}}
if($('#fullpage').length){$.fn.fullpage.setAllowScrolling(!0)}
$('.page-helper').show()}});$('.portfolio--cube, .section-portfolio').slickLightbox({itemSelector:'.portfolio-item-hover-block',navigateByKeyboard:!0,}).on({'show.slickLightbox':function(){$('body').addClass('no-scroll');if(!$('body').hasClass('fullpage-page')&&!$('body').hasClass('cube-page')){$('body, .header-wrap').css('padding-right',widthOfScrollbar)}
if(navigator.appName==='Microsoft Internet Explorer'||!!(navigator.userAgent.match(/Trident/)||navigator.userAgent.match(/rv:11/))||(typeof $.browser!=="undefined"&&$.browser.msie===1)){$('body, .header-wrap').css('padding-right',widthOfScrollbar)}},'hide.slickLightbox':function(){$('body').removeClass('no-scroll');if(!$('body').hasClass('fullpage-page')&&!$('body').hasClass('cube-page')){$('body, .header-wrap').css('padding-right','0')}
if(navigator.appName==='Microsoft Internet Explorer'||!!(navigator.userAgent.match(/Trident/)||navigator.userAgent.match(/rv:11/))||(typeof $.browser!=="undefined"&&$.browser.msie===1)){$('body, .header-wrap').css('padding-right','0')}}});$('.testimonials-slider').slick({slidesToShow:1,slidesToScroll:1,dots:!0,arrows:!1,draggable:!1,speed:1000,autoplay:!0,autoplaySpeed:4000,});$('input:not([type="submit"]) , textarea').on('blur',function(){if(!$(this).val()){$(this).removeClass('active')}else{$(this).addClass('active')}});function arrowScroll(){if($('.js-header').hasClass('.-small')){var topLineHeight=$('.js-header').outerHeight();$('html, body').animate({scrollTop:$("#about-us").offset().top-topLineHeight},1000)}else{var topLineHeight=$('.js-header').outerHeight(),topPaddingOfHeader=parseInt($('.js-header').css("padding-top")),bottomPaddingOfHeader=parseInt($('.js-header').css("padding-bottom"));$('html, body').animate({scrollTop:$("#about-us").offset().top-topLineHeight+topPaddingOfHeader+bottomPaddingOfHeader},1000)}}
$('.js-arrow-down-cube').on('click',function(e){if($(window).width()<=991){arrowScroll();e.stopPropagation()}});$('.js-arrow-down-flat').on('click',function(){arrowScroll()});$('.js-arrow-down-fullpage').on('click',function(){if($(window).width()<=991){arrowScroll()}
if($(window).width()>991&&$('#fullpage').length){$.fn.fullpage.moveSectionDown()}});function textAnimation(){var waypoints=$('.wrap-for-animation').waypoint({handler:function(){$(this.element).find(".side-animation-item").addClass("side-animation-action")},offset:'90%'})}
if($('body').hasClass('flat-page')){textAnimation()}
var sections=$('.-section');for(var i=0;i<sections.length;i++){var tooltip=sections[i].getAttribute("data-tooltip");var child=$(sections[i]).children(".bg_letter");if(child.length!==0)
{child.text(tooltip.charAt(0))}}
var sections=$('.indicators-section .count-item');for(var i=0;i<sections.length;i++){var tooltip=$(sections[i]).find(".js-count-title").text();var child=$(sections[i]).children(".bg_letter");if(child.length!==0)
{child.text(tooltip.charAt(0))}}
$('.btn-top').on('click',function(){$('body, html').animate({scrollTop:0},1000);return!1});var stopFunction=!1;function barsAnimation(){if(stopFunction===!1){var barsDuration=3500;stopFunction=!0;$('.bars-block-wrap .bar-item').each(function(){var $percent=$(this).find(".bar-strip").attr('data-percentage');$(this).find('.tooltip-item').animate({left:$percent+"%"},barsDuration);var $numberItem=$(this).find(".percent");$({Counter:0}).animate({Counter:$percent},{duration:barsDuration,easing:'swing',step:function(){$numberItem.text(Math.ceil(this.Counter))}})})}}
var waypoints=$('.main-content-page .bars-block-wrap, .flat-page .bars-block-wrap').waypoint({handler:function(){barsAnimation()},offset:'80%'})
if(screen.width<=991){var waypoints=$('.cube-page .bars-block-wrap').waypoint({handler:function(){barsAnimation()},offset:'80%'})}
$(window).on('resize',function(){if(screen.width<=991){var waypoints=$('.cube-page .bars-block-wrap').waypoint({handler:function(){barsAnimation()},offset:'80%'})}});$(window).on('scroll',function(){if($(this).scrollTop()>0){$('.header').addClass('-small');$(".btn-top").addClass('-show')}else{$('.header').removeClass('-small');$(".btn-top").removeClass('-show')}})
if($(this).scrollTop()>0){$('.header').addClass('-small');$(".btn-top").addClass('-show')}
if($('#fullpage').length){$('#fullpage').fullpage({scrollingSpeed:1000,responsiveWidth:992,responsiveHeight:600,verticalCentered:!1,navigation:!0,navigationTooltips:!0,showActiveTooltip:!0,sectionSelector:'.page',fixedElements:'#fullPageModal, .btn-top',onLeave:function(index,nextIndex,direction){$('#fp-nav > ul > li').removeClass('active-item');$('#fp-nav > ul > li')[nextIndex-1].classList.add('active-item');$(".-section[data-index="+nextIndex+"] .side-animation-item").addClass('side-animation-action');barsAnimation()}});$('.-JS_helper_click').on('click',function(){if($(this).parents('.page-helper').hasClass('-open')){$.fn.fullpage.setAllowScrolling(!1)}else{$.fn.fullpage.setAllowScrolling(!0)}});$('#fp-nav > ul').addClass('bullets_menu');$('#fp-nav > ul > li').append($('<span class="page-title"></span>'));$('#fp-nav > ul > li').append($('<span class="stick"></span>'));$('#fp-nav > ul > li').append($('<span class="hover-title"></span>'));$('#fp-nav > ul > li > a').each(function(){if($(this).hasClass('active')){$(this).closest('li').addClass('active-item')}});var i=0;$('#fp-nav .fp-tooltip').each(function(){var sectionTitle=$(this).text();$('.page-title')[i].innerHTML=sectionTitle;$('.hover-title')[i].innerHTML=sectionTitle;i++})}
if(navigator.appName==='Microsoft Internet Explorer'||!!(navigator.userAgent.match(/Trident/)||navigator.userAgent.match(/rv:11/))||(typeof $.browser!=="undefined"&&$.browser.msie===1)){textAnimation();var waypoints=$('.cube-page .bars-block-wrap').waypoint({handler:function(){barsAnimation()},offset:'80%'})
$('.js-arrow-down-cube').on('click',function(e){arrowScroll();e.stopPropagation()});$("#menu_btn--js").on("click",function(){if($('#fullPageMenu').hasClass('-open-menu')){$('body, .header-wrap').css('padding-right',widthOfScrollbar)}
else{$('body, .header-wrap').css('padding-right','0')}})}})}(jQuery))